#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.1.{build}

# Do not increment version number for each pull request. Instead add a random string
pull_requests:
  do_not_increment_build_number: true

# branches to build  
branches:
  only:
    - master

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

  
#---------------------------------#
#    environment configuration    #
#---------------------------------#

image:
- Visual Studio 2017

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform:
  - Any CPU

configuration:
  - Release

build:
  project: Source\SharpVectors.sln
  publish_nuget: true
  publish_nuget_symbols: true

after_build:
  - ps: nuget pack "Source\SharpVectors.nuspec" -Properties "version=$env:appveyor_build_version"

#---------------------------------#
#      packaging artifacts        #
#---------------------------------#

artifacts:
  - path: '**\*.nupkg'
